version: "3.8"

services:
  jupyter:
    build: ./jupyter-docker
    ports:
      - 8789:8888
    volumes:
      - ./notebooks:/home/jovyan
      - ./personas:/home/jovyan/personas
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: "entrypoint.sh"
  fuzzy-entity-resolver:
    build: submodules/knowledge-services/fuzzy-entity-resolver
  kbqa-service:
    build: submodules/kbqa
  mongo:
    image: mongo:5.0.2-focal
    restart: always
