version: "3.8"

services:
  jupyter:
    image: jupyter/minimal-notebook:2021-10-11
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan
      - ./personas:/home/jovyan/personas
    command: ["start-notebook.sh", "--NotebookApp.token=''", "--NotebookApp.password=''"]
  fuzzy-entity-resolver:
    build: submodules/knowledge-services/fuzzy-entity-resolver
  kbqa-service:
    build: submodules/kbqa
